#!/usr/bin/env python3
"""Generate the build 12340 encounter-to-creature/spell supplement.

The generated table contains only numeric joins. Runtime code still validates
every encounter and spell against the active build 12340 DBC stores before it
publishes the record to Lua.
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys


INSTANCE_ROW = re.compile(r"^\((\d+),(\d+),(\d+),")
SPELL_ROW = re.compile(r"^\((\d+),(\d+),(\d+|NULL),(NULL|-?\d+)\)[,;]$")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--instance-encounters", required=True, type=pathlib.Path)
    parser.add_argument("--creature-spells", required=True, type=pathlib.Path)
    parser.add_argument("--output", required=True, type=pathlib.Path)
    return parser.parse_args()


def parse_instance_encounters(path: pathlib.Path) -> dict[int, int]:
    result: dict[int, int] = {}
    row_count = 0
    for line_number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        if not line.startswith("("):
            continue
        match = INSTANCE_ROW.match(line)
        if match is None:
            raise ValueError(f"{path}:{line_number}: unsupported instance row")
        row_count += 1
        encounter_id, credit_type, credit_entry = map(int, match.groups())
        if encounter_id in result:
            raise ValueError(f"{path}:{line_number}: duplicate encounter {encounter_id}")
        if credit_type == 0 and credit_entry != 0:
            result[encounter_id] = credit_entry
    if row_count == 0:
        raise ValueError(f"{path}: no instance encounter rows found")
    return result


def parse_creature_spells(
    path: pathlib.Path, creature_ids: set[int]
) -> dict[int, list[tuple[int, int, int]]]:
    result: dict[int, list[tuple[int, int, int]]] = {}
    row_count = 0
    for line_number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        if not line.startswith("("):
            continue
        match = SPELL_ROW.match(line)
        if match is None:
            raise ValueError(f"{path}:{line_number}: unsupported creature spell row")
        row_count += 1
        creature_id = int(match.group(1))
        if creature_id not in creature_ids:
            continue
        index = int(match.group(2))
        spell_text = match.group(3)
        build_text = match.group(4)
        if index > 7:
            raise ValueError(f"{path}:{line_number}: spell index {index} is out of range")
        if spell_text == "NULL" or int(spell_text) == 0:
            continue
        verified_build = 0 if build_text == "NULL" else int(build_text)
        result.setdefault(creature_id, []).append(
            (index, int(spell_text), verified_build)
        )
    if row_count == 0:
        raise ValueError(f"{path}: no creature spell rows found")
    for creature_id, spells in result.items():
        indices = [entry[0] for entry in spells]
        if len(indices) != len(set(indices)):
            raise ValueError(f"{path}: duplicate spell index for creature {creature_id}")
        spells.sort()
    return result


def render(
    encounter_creatures: dict[int, int],
    creature_spells: dict[int, list[tuple[int, int, int]]],
) -> str:
    rows: list[str] = []
    for encounter_id, creature_id in sorted(encounter_creatures.items()):
        spells = creature_spells.get(creature_id, [])
        padded_spells = [
            f"JournalSupplementSpell{{{spell_id}u, {verified_build}}}"
            for _, spell_id, verified_build in spells
        ]
        padded_spells.extend(
            "JournalSupplementSpell{}" for _ in range(8 - len(padded_spells))
        )
        rendered_spells = ", ".join(padded_spells)
        rows.append(
            "    JournalEncounterSupplement{"
            f"{encounter_id}u, {creature_id}u, "
            f"std::array{{{rendered_spells}}}, {len(spells)}u" "},"
        )

    return "\n".join(
        [
            "// Generated by tools/encounter_journal/generate_build12340_catalog.py.",
            "// Numeric server mappings are supplemental; runtime publication is",
            "// gated by the active build 12340 DungeonEncounter/Spell DBC records.",
            "constexpr auto kJournalEncounterSupplements = std::array{",
            *rows,
            "};",
            "",
        ]
    )


def main() -> int:
    args = parse_args()
    try:
        encounter_creatures = parse_instance_encounters(args.instance_encounters)
        creature_spells = parse_creature_spells(
            args.creature_spells, set(encounter_creatures.values())
        )
        output = render(encounter_creatures, creature_spells)
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(output, encoding="utf-8")
    except (OSError, ValueError) as error:
        print(error, file=sys.stderr)
        return 1
    print(
        f"wrote {len(encounter_creatures)} encounter mappings to {args.output}",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
